[tool.poetry]
name = "plumes"
version = "0.1.0"
description = "Simple Twitter CLI for day-to-day tasks and social media hygiene"
authors = ["Nicholas Nadeau <nicholas.nadeau@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.6.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
